version: "3.7"
services:
  app:
    image: @project.artifactId@:@project.version@
    ports: 
      - 8080:8080
      - 9090:9090
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.20'
          memory: 128M
      mode: replicated
      replicas: 1
    depends_on: <% if (mongodb) { %>
      - mongodb<% } if (rabbit) { %>
      - rabbitmq<% } if (kafka) { %>
      - kafka<% } if (redis) { %>
      - redis<% } if (postgres) { %>
      - postgres<% } if (metricsinflux) { %>
      - influxdb<% } %>
    networks:
      - backend
      - frontend <% if (kafka || rabbit) { %>
      - message<% } %>
    links: <% if (mongodb) { %>
      - mongodb:mongodb<% } if (postgres) { %>
      - postgres:postgres<% } if (redis) { %>
      - redis:redis<% } if (kafka) { %>
      - kafka:kafka<% } if (rabbit) { %>
      - rabbit:rabbit<% } if (metricsinflux) { %>
      - influxdb:influxdb<% } if (metricsinflux) { %>
  influxdb:
    image: influxdb:1.7.5-alpine
    ports: 
      - 8086:8086
      - 8083:8083
    networks:
      - backend
    volumes:
      - influxdbdata:/var/lib/influxdb
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.20'
          memory: 128M
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]<% } if (postgres) { %>
  postgres:
    image: postgres:11.2-alpine
    ports: 
      - 5432:5432
    networks:
      - backend
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=<%=randomPasswd%>
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.20'
          memory: 128M
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]<% } if (redis) { %>
  redis:
    image: redis:5.0.4-alpine
    ports: 
      - 6379:6379
    networks:
      - backend
    volumes:
      - redisdata:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.20'
          memory: 128M
      mode: replicated
      replicas: 1<% } if (mongodb) { %>
  mongodb:
    image: bitnami/mongodb:4.1
    ports: 
      - 27017:27017
    environment:
      - MONGODB_USERNAME=<%=artifact%>
      - MONGODB_PASSWORD=<%=randomPasswd%>
      - MONGODB_DATABASE=<%=artifact%>
    networks:
      - backend
    volumes:
      - mongodbdata:/bitnami
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.20'
          memory: 128M
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]<% } if (rabbit) { %>
  rabbitmq:
    image: rabbitmq:3.7.14-management-alpine
    ports: 
      - 5672:5672
      - 15672:15672
    environment: 
      - RABBITMQ_DEFAULT_USER=<%=artifact%>
      - RABBITMQ_DEFAULT_PASS=<%=randomPasswd%>
    networks:
      - message
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.20'
          memory: 128M
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]<% } if (kafka) { %>
  kafka:
    image: spotify/kafka
    ports: 
      - 2181
      - 9092
    environment: 
      - ADVERTISED_HOST=localhost
      - ADVERTISED_PORT=9092
    networks:
      - message
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]<% } %>
networks:
  backend:
  frontend: <% if (kafka || rabbit) { %>
  message:<% } %>
volumes: <% if (postgres) { %>
  postgresdata: <% } if (redis) { %>
  redisdata: <% } if (mongodb) { %>
  mongodbdata: <% } if (rabbit) { %>
  rabbitdata: <% } if (metricsinflux) { %>
  influxdbdata: <% } %>