version: "3.7"
services:
  app:
    image: @project.artifactId@:@project.version@
    ports: 
      - 8080:8080
      - 9090:9090
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.20'
          memory: 128M
      mode: replicated
      replicas: 1
    depends_on:
      <% if (metricsinflux) { %>- influxdb<% } %>
      <% if (postgres) { %>- postgres<% } %>
      <% if (mysql) { %>- mysql<% } %>
      <% if (redis) { %>- redis<% } %>
    networks:
      - backend
      - frontend
    links:
      <% if (metricsinflux) { %>- influxdb:influxdb<% } %>
      <% if (postgres) { %>- postgres:postgres<% } %>
      <% if (mysql) { %>- mysql:mysql<% } %>
      <% if (redis) { %>- redis:redis<% } %>
  <% if (metricsinflux) { %>influxdb:
    image: influxdb:1.7.5-alpine
    ports: 
      - 8086:8086
      - 8083:8083
    networks:
      - backend
    volumes:
      - influxdbdata:/var/lib/influxdb
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.20'
          memory: 128M
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]<% } %>
  <% if (postgres) { %>postgres:
    image: postgres:11.2-alpine
    ports: 
      - 5432:5432
    networks:
      - backend
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=pgdb<%=artifact%>@123"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.20'
          memory: 128M
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]<% } %>
  <% if (mysql) { %>mysql:
    image: mysql:8.0.15
    ports: 
      - 3306:3306
    networks:
      - backend
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=mydb<%=artifact%>@123"
      - "MYSQL_DATABASE=<%=artifact%>"
      - "MYSQL_USER=<%=artifact%>"
      - "MYSQL_PASSWORD=mydb<%=artifact%>@123"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.20'
          memory: 128M
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]<% } %>
  <% if (redis) { %>redis:
    image: redis:5.0.4-alpine
    ports: 
      - 6379:6379
    networks:
      - backend
    volumes:
      - redisdata:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.20'
          memory: 128M
      mode: replicated
      replicas: 1<% } %>
networks:
  backend:
  frontend:
volumes:
  <% if (postgres) { %>postgresdata:<% } %>
  <% if (mysql) { %>mysqldata:<% } %>
  <% if (metricsinflux) { %>influxdbdata:<% } %>
  <% if (redis) { %>redisdata:<% } %>
