logging:
  level:
    <%= packageroot %>: INFO
    org.springframework.boot.context: INFO
server:
  compression:
    enabled: true
  port: 8080
  servlet: 
    context-path: /<%= artifact %>
<% if (swagger) { %>springfox:
  documentation:
    swagger.v2.path: /v2/api-docs
    info:
      title: 
      description: <%= apptitle %> Docs.
      version: 1.0
    base-package: <%= packageroot %><% } %>
<% if (actuator || metricsinflux) { %>management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'<% } %>
<% if (metricsinflux) { %>  metrics:
    export:
      influx:
        db: <%=artifact%>
        uri: http://<%=artifact%>_influxdb:8086<% } %>
spring:
  messages:
    basename: i18n/messages
<% if (redis) { %>  cache:
    type: redis<% } %>
<% if (mongodb) { %>  data:
    mongodb:
      host: <%=artifact%>_mongodb
      port: 27017
      database: <%=artifact%>
      username: mongouser
      password: mongodb<%=artifact%>@123<% } %>
<% if (rabbit) { %>  rabbitmq:
    host: <%=artifact%>_rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    writeQueue: rabbit-queue
    readQueue: rabbit-dead-queue
    exchange: rabbit-exchange
    connection-timeout: 9000<% } %>
<% if (postgres) { %>  datasource:
    platform: postgresql
    url: jdbc:postgresql://<%=artifact%>_postgres:5432/postgres
    username: postgres
    password: pgdb<%=artifact%>@123
    continue-on-error: true<% } %>
<% if (jpa) { %>  jpa:
    hibernate:
      ddl-auto: update
    database: <%=databaseJpa%>
    database-platform: org.hibernate.dialect.<%=databaseDialect%>
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true<% } %>
<% if (kafka) { %>  kafka:
    consumer:
      bootstrap-servers: <%=artifact%>_kafka:9092
      group-id: <%=kafkaGroupId%>
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: <%=artifact%>_kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer<% } %>